GLB_GUI_USE_APPENDIX_C: 0
GLB_GUI_USE_APPENDIX_C_LWC_FACTOR: 0
GLB_GUI_USE_APPENDIX_D: 0
GLB_GUI_USE_APPENDIX_D_TWC_FACTOR: 0
GLB_GUI_USE_APPENDIX_O: 0
GLB_GUI_USE_APPENDIX_O_LWC_FACTOR: 0
GLB_GUI_APPENDIX_SWITCH: 0
