# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Oder 3.13 wenn verfügbar, aber 3.11 ist stabil
  sphinx:
    configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
