PWS_AIRFOIL_FILE: ../_data/AH63K127.dat
PWS_PROFILE1: ../_data/AH63K127_densened.dat
PWS_PROFILE2: ../_data/AH63K127_thickened.dat
PWS_POLAR_FILE: pol_output.pol
PWS_SUCTION_FILE: psi_output.pol
PWS_INI_NUM_PANELS: 400
PWS_INI_TE_YPLUS: 0.0005
PWS_INI_TE_YMINUS: -0.0005
PWS_TE_GAP: 0.00232018561
PWS_TE_BLENDING: 0.6
PWS_POL_REYNOLDS: 1.47e6
PWS_POL_MACH: 0.15
PWS_POL_ITER: 100
PWS_POL_ALPHA_START: -2
PWS_POL_ALPHA_END: 10
PWS_POL_ALPHA_STEP: 1
PWS_PSI_REYNOLDS: 1.47e6
PWS_PSI_MACH: 0.15
PWS_PSI_ITER: 100
PWS_PSI_ALPHA_START: 4
PWS_PSI_ALPHA_END: 10
PWS_PSI_ALPHA_STEP: 1
PWS_PROF_PATH: ../_data/AH63K127_processed.dat
PWS_GRID_PATH: ../mesh/GCI.cas
PWS_PROJ_PATH: ../pointwise/GCI.pw
PWS_CHORD_LENGTH: 0.431
PWS_SPLIT_PERCENTAGE: 0.4
PWS_FF_FACTOR: 20
PWS_FF_DIMENSION: 600
PWS_DIM_BACK_CONNECTORS: 160
PWS_UPPER_FRONT_DIM: 160
PWS_UPPER_BACK_DIM: 160
PWS_LOWER_FRONT_DIM: 160
PWS_LOWER_BACK_DIM: 160
PWS_TE_DIM: 8
PWS_SPACING_1: 0.0001
PWS_SPACING_2: 0.0001
PWS_REFINEMENT: 16
PWS_TREX_FIRST_HEIGHT: 1.8026e-06
PWS_TREX_GROWTH_RATE_COND: 1.15
PWS_TREX_MAX_LAYERS: 500
PWS_TREX_FULL_LAYERS: 10
PWS_TREX_GROWTH_RATE_ATTR: 1.15
PWS_SIZE_FIELD_DECAY: 0.95
