# solver_vars.yaml  – flach & exakt gleiche Schreibweise
SEQ_END_CONDITION: 0
SEQ_GRID_FILE: ../single.grid
SEQ_GRID_FILE_ORIG_FORMAT: ../single.cas
SEQ_GRID_FILE_TIMESTAMP: 676595280
SEQ_GRID_FILE_WALL_TEMP: 0
SEQ_GRID_FILE_WALL_ZONES: 0
SEQ_IO_ITERATIONRESTART: 1
SEQ_IO_RESTART: 0
SEQ_MAX_LOOP: 1

SEQ_VALUE_VAR1: [2, 100, 100]

SEQ_VARIABLES:
  - ICE_GUI_TOTAL_TIME

SEQ_VARIABLES_RUN:
  - ice
