skinparam backgroundColor #0F172A
skinparam shadowing false
skinparam roundcorner 10

skinparam class {
  BackgroundColor #020617
  BorderColor #38BDF8
  ArrowColor #38BDF8
  FontColor #E5E7EB
  FontSize 13
}

skinparam classAttribute {
  FontColor #E5E7EB
}

skinparam classMethod {
  FontColor #E5E7EB
}

skinparam package {
  BackgroundColor #020617
  BorderColor #64748B
  FontColor #E5E7EB
}

skinparam ArrowThickness 1.2
skinparam linetype ortho
left to right direction