DRP_GUI_CFL: 20
DRP_GUI_ARTIFICIAL_VISCOSITY_IN_RESIDUAL: 1e-5
DRP_GUI_INITIAL_TYPE: 0
DRP_GUI_BC_DIAM: 3 "20" "" ""
DRP_GUI_BC_DIAM_CRYSTALS: 3 "100" "" ""
DRP_GUI_BC_DIAM_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_DIAM_FLAG: 3 1 1 1
DRP_GUI_BC_LWC: 3 "0.001" "" ""
DRP_GUI_BC_LWC_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_LWC_FLAG: 3 1 1 1
DRP_GUI_BC_MELTF_CRYSTALS_FLAG: 3 0 1 1
DRP_GUI_BC_TEMP: 3 "288" "" ""
DRP_GUI_BC_TEMP_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_TEMP_FLAG: 3 1 1 1
DRP_GUI_BC_VAPOR_INIT_TYPE: 3 2 2 2
DRP_GUI_BC_VAP_CONC: 3 "0.001" "" ""
DRP_GUI_BC_VAP_CONC_FLAG: 3 1 1 1
DRP_GUI_BC_VAP_RH: 3 "100" "" ""
DRP_GUI_BC_VAP_RH_FLAG: 3 1 1 1
DRP_GUI_BC_VAP_WETBULB: 3 "265" "" ""
DRP_GUI_BC_VAP_WETBULB_FLAG: 3 1 1 1
DRP_GUI_BC_VX: 3 "0" "" ""
DRP_GUI_BC_VX_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_VX_FLAG: 3 1 1 1
DRP_GUI_BC_VY: 3 "0" "" ""
DRP_GUI_BC_VY_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_VY_FLAG: 3 1 1 1
DRP_GUI_BC_VZ: 3 "0" "" ""
DRP_GUI_BC_VZ_CRYSTALS_FLAG: 3 1 1 1
DRP_GUI_BC_VZ_FLAG: 3 1 1 1
DRP_GUI_ITERATIONS_BETWEEN_PRINTOUTS: 40
DRP_GUI_PRINTOUT_MODE: 0
DRP_GUI_CRYSTAL_DISTRIBUTION: 0
DRP_GUI_DROPLET_DISTRIBUTION: 0
DRP_GUI_DROPLET_NUMBER: 0
DRP_GUI_USER_CRYSTAL_AR_DIST: 2 0.05 0.05
DRP_GUI_USER_CRYSTAL_DIST: 0
DRP_GUI_USER_DROPLET_MVD: 0
DRP_GUI_USER_DROPLET_PERCENTILE: 0
DRP_GUI_USER_DROPLET_RUN_FLAG: 0
