FSP_GUI_PHYSICAL_MODEL:
  - "Air"
  - "Droplets"
  - "Air+Droplets"
FSP_GUI_PHYSICAL_MODEL_MOMENTUM_EQUATION:
  - "Euler"
  - "Navier-Stokes"
FSP_GUI_PHYSICAL_MODEL_ENERGY_EQUATION:
  - "Full PDE"
  - "Constant Enthalpy"
  - "Energy Only"
FSP_GUI_TURBULENCE_MODEL:
  - "Laminar"
  - "Spalart Allmaras"
  - "Low Reynolds K-Omega"
  - "K-omega SST"
FSP_GUI_TURBULENCE_MODEL_SA_EDDY_VISCOSITY_RATIO
FSP_GUI_TURBULENCE_MODEL_SA_RELAXATION_FACTOR
FSP_GUI_TURBULENCE_MODEL_SA_NUMBER_ITERATIONS
FSP_GUI_TURBULENCE_MODEL_LOW_RE_KO_EDDY_VISCOSITY_RATIO
FSP_GUI_TURBULENCE_MODEL_LOW_RE_KO_TURBULENCE_INTENSITY
FSP_GUI_TURBULENCE_MODEL_LOW_RE_KO_RELAXATION_FACTOR
FSP_GUI_TURBULENCE_MODEL_LOW_RE_KO_
