"""Create a clean angle-of-attack sweep for the full power study.

The sweep skips the precomputed AoA=0 case which must be generated by
``07_aoa0_projects.py``.  It reuses the mesh from the most detailed
multishot project and computes the remaining angles.

Inputs
------
base_dir : Path | str, optional
    Base directory containing ``05_multishot`` and ``07_clean_aoa0``.
case_vars : dict[str, Any] | None, optional
    Case variable overrides passed to each project.

Outputs
-------
Projects created under ``08_clean_sweep``.

Usage
-----
``python scripts/08_clean_sweep_creation.py``

Run ``07_aoa0_projects.py`` beforehand to supply the AoA=0 baseline for
subsequent plots.

See Also
--------
``docs/full_power_study.rst`` for a complete workflow example.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from glacium.api import Project
from glacium.utils import reuse_mesh, run_aoa_sweep
from glacium.utils.logging import log
from glacium.managers.project_manager import ProjectManager

from multishot_loader import load_multishot_project


def main(
    base_dir: Path | str = Path(""), case_vars: dict[str, Any] | None = None
) -> None:
    """Create AOA sweep projects using the AoA=0 baseline run.

    Parameters
    ----------
    base_dir : Path | str, optional
        Directory containing ``05_multishot`` and ``07_clean_aoa0`` where the
        ``08_clean_sweep`` project will be created.
    case_vars : dict[str, Any] | None, optional
        Case variables overriding those read from the baseline project.
    """

    base_path = Path(base_dir)
    src_root = base_path / "07_clean_aoa0"

    pm = ProjectManager(src_root)
    uids = pm.list_uids()
    if not uids:
        log.error(f"No projects found in {src_root}")
        return
    baseline_project = Project.load(src_root, uids[0])
    precomputed = {0.0: baseline_project}

    try:
        ms_project = load_multishot_project(base_path / "05_multishot")
    except FileNotFoundError as err:
        log.error(str(err))
        return
    mesh_path = ms_project.get_mesh()

    sweep_root = base_path / "08_clean_sweep"

    base = baseline_project.clone().name("aoa_sweep")
    base.runs_root = sweep_root
    base._params.pop("FSP_FILES_GRID", None)
    base._params.pop("ICE_GRID_FILE", None)  # safe no-op for clean case
    base._params.pop("LIFT_COEFFICIENT", None)
    base._params.pop("DRAG_COEFFICIENT", None)
    base._jobs = []  # type: ignore[attr-defined]

    if case_vars:
        for key, val in case_vars.items():
            base.set(key, val)

    jobs = ["FENSAP_CONVERGENCE_STATS", "FENSAP_ANALYSIS"]
    mesh = lambda proj: reuse_mesh(proj, mesh_path, "FENSAP_RUN")
    run_aoa_sweep(
        base,
        aoa_start=-4.0,
        aoa_end=16.0,
        step_sizes=[2.0, 1.0, 0.5],
        jobs=jobs,
        postprocess_aoas=set(),
        mesh_hook=mesh,
        skip_aoas={0.0},
        precomputed=precomputed,
    )


if __name__ == "__main__":
    main()
