"""Create a clean angle-of-attack sweep for the full power study.

The sweep skips the precomputed AoA=0 case which must be generated by
``07_aoa0_projects.py``.  It reuses the mesh from the most detailed
multishot project and computes the remaining angles.

Inputs
------
base_dir : Path | str, optional
    Base directory containing ``05_multishot`` and ``07_clean_aoa0``.
case_vars : dict[str, Any] | None, optional
    Case variable overrides passed to each project.

Outputs
-------
Projects created under ``08_clean_sweep``.

Usage
-----
``python scripts/08_clean_sweep_creation.py``

Run ``07_aoa0_projects.py`` beforehand to supply the AoA=0 baseline for
subsequent plots.

See Also
--------
``docs/full_power_study.rst`` for a complete workflow example.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from glacium.api import Project
from glacium.utils import reuse_mesh, run_aoa_sweep
from glacium.utils.logging import log
from glacium.managers.project_manager import ProjectManager
from glacium.managers.config_manager import ConfigManager

from multishot_loader import load_multishot_project


def main(
    base_dir: Path | str = Path(""), case_vars: dict[str, Any] | None = None
) -> None:
    """Create AOA sweep projects using the AoA=0 baseline run.

    Parameters
    ----------
    base_dir : Path | str, optional
        Directory containing ``05_multishot`` and ``07_clean_aoa0`` where the
        ``08_clean_sweep`` project will be created.
    case_vars : dict[str, Any] | None, optional
        Case variables overriding those read from the baseline project.
    """

    base_path = Path(base_dir)
    src_root = base_path / "07_clean_aoa0"

    pm = ProjectManager(src_root)
    uids = pm.list_uids()
    if not uids:
        log.error(f"No projects found in {src_root}")
        return
    baseline_project = Project.load(src_root, uids[0])
    precomputed = {0.0: baseline_project}

    try:
        ms_project = load_multishot_project(base_path / "05_multishot")
    except FileNotFoundError as err:
        log.error(str(err))
        return
    mesh_path = ms_project.get_mesh()

    sweep_root = base_path / "08_clean_sweep"

    params: dict[str, Any] = {}

    # collect parameters from the baseline project using the public API
    if hasattr(baseline_project, "get"):
        case_file = getattr(baseline_project, "root", None)
        if case_file is not None:
            case_file = Path(case_file) / "case.yaml"
            if case_file.exists():
                case_data = yaml.safe_load(case_file.read_text()) or {}
                for key in case_data.keys():
                    try:
                        params[key.upper()] = baseline_project.get(key)
                    except Exception:
                        pass
        try:
            cfg_mgr = ConfigManager(baseline_project.paths)  # type: ignore[attr-defined]
            global_cfg = cfg_mgr.load_global()
            for key in getattr(global_cfg, "extras", {}).keys():
                ukey = key.upper()
                try:
                    params[ukey] = baseline_project.get(ukey)
                except Exception:
                    pass
            try:
                params["RECIPE"] = baseline_project.get("RECIPE")
            except Exception:
                pass
        except Exception:
            # fall back to just attempting to copy the recipe
            try:
                params["RECIPE"] = baseline_project.get("RECIPE")
            except Exception:
                pass

    for rm in (
        "FSP_FILES_GRID",
        "ICE_GRID_FILE",
        "LIFT_COEFFICIENT",
        "DRAG_COEFFICIENT",
    ):
        params.pop(rm, None)

    base = Project(sweep_root).name("aoa_sweep").set_bulk(params)

    if case_vars:
        base.set_bulk(case_vars)

    jobs = ["FENSAP_CONVERGENCE_STATS", "FENSAP_ANALYSIS"]
    mesh = lambda proj: reuse_mesh(proj, mesh_path, "FENSAP_RUN")
    run_aoa_sweep(
        base,
        aoa_start=-4.0,
        aoa_end=16.0,
        step_sizes=[2.0, 1.0, 0.5],
        jobs=jobs,
        postprocess_aoas=set(),
        mesh_hook=mesh,
        skip_aoas={0.0},
        precomputed=precomputed,
    )


if __name__ == "__main__":
    main()
