"""Create an iced angle-of-attack sweep for the full power study.

The :func:`main` entry point retrieves the latest iced grid generated by
the multishot simulation and runs FENSAP cases over a range of angles of
attack.

Key Functions
-------------
* :func:`get_last_iced_grid` – locate the iced grid with the highest
  numeric suffix.
* :func:`main` – command line interface.

Inputs
------
base_dir : Path | str, optional
    Base directory containing ``05_multishot``.
case_vars : dict[str, Any] | None, optional
    Case variable overrides.

Outputs
-------
Projects created under ``09_iced_sweep``.

Usage
-----
``python scripts/09_iced_sweep_creation.py``

See Also
--------
``docs/full_power_study.rst`` for a complete workflow example.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import re

from glacium.api import Project
from glacium.managers.project_manager import ProjectManager
from glacium.utils import reuse_mesh, run_aoa_sweep
from glacium.utils.logging import log

from multishot_loader import load_multishot_project


def get_last_iced_grid(project: Project) -> Path:
    """Return the iced grid with the highest numeric suffix."""
    iced_dir = project.root / "run_MULTISHOT"
    pattern = re.compile(r"grid\.ice\.(\d{6})$")
    best: tuple[int, Path] | None = None
    for entry in iced_dir.iterdir():
        match = pattern.fullmatch(entry.name)
        if match:
            idx = int(match.group(1))
            if best is None or idx > best[0]:
                best = (idx, entry)
    if best is None:
        raise FileNotFoundError(f"No iced grid found in {iced_dir}")
    return best[1]


def main(
    base_dir: Path | str = Path(""), case_vars: dict[str, Any] | None = None
) -> None:
    """Create AOA sweep using the last iced grid from the multishot project."""

    base_path = Path(base_dir)

    try:
        ms_project = load_multishot_project(base_path / "05_multishot")
    except FileNotFoundError as err:
        log.error(str(err))
        return

    grid_path = get_last_iced_grid(ms_project)
    match = re.search(r"grid\.ice\.(\d{6})$", grid_path.name)
    if not match:
        log.error("Could not determine shot index from %s", grid_path)
        return
    shot_index = match.group(1)
    roughness_path = grid_path.with_name(f"roughness.dat.ice.{shot_index}")
    if not roughness_path.exists():
        log.error("Missing roughness file for shot %s: %s", shot_index, roughness_path)
        return

    base = Project(base_path / "10_iced_sweep").name("aoa_sweep")
    base.set("RECIPE", "fensap")

    get = getattr(ms_project, "get", lambda _k: None)
    params = {
        "CASE_CHARACTERISTIC_LENGTH": get("CASE_CHARACTERISTIC_LENGTH"),
        "CASE_VELOCITY": get("CASE_VELOCITY"),
        "CASE_ALTITUDE": get("CASE_ALTITUDE"),
        "CASE_TEMPERATURE": get("CASE_TEMPERATURE"),
        "CASE_YPLUS": get("CASE_YPLUS"),
        "PWS_REFINEMENT": get("PWS_REFINEMENT"),
    }
    if case_vars:
        params.update(case_vars)

    for key, val in params.items():
        base.set(key, val)

    jobs = ["FENSAP_CONVERGENCE_STATS"]
    mesh = lambda proj: reuse_mesh(
        proj, grid_path, "FENSAP_RUN", roughness=roughness_path
    )

    pm = ProjectManager(base_path / "07_iced_aoa0")
    baseline_uid = pm.list_uids()[0]
    baseline_project = Project.load(base_path / "07_iced_aoa0", baseline_uid)
    precomputed = {0.0: baseline_project}
    skip_aoas = {}

    run_aoa_sweep(
        base,
        aoa_start=-4,
        aoa_end=16.0,
        step_sizes=[2.0, 1.0, 0.5],
        jobs=jobs,
        postprocess_aoas=set(),
        skip_aoas=skip_aoas,
        precomputed=precomputed,
        mesh_hook=mesh,
    )


if __name__ == "__main__":
    main()
