defaults:
  - pws@_global_: default
  - pointwise@_global_: default
  - fensap@_global_: default
  - fluent2fensap@_global_: default
  - xfoil@_global_: default
  - fsp@_global_: default
  - ice@_global_: default
  - glb@_global_: default
  - smc@_global_: default
  - msh@_global_: default
  - drp@_global_: default
