# Input
CASE_ROUGHNESS: 0.001
CASE_CHARACTERISTIC_LENGTH: 0.431
CASE_VELOCITY: 50
CASE_ALTITUDE: 100
CASE_TEMPERATURE: 270
CASE_AOA: 4
CASE_MVD: 20
CASE_LWC: 0.001
CASE_YPLUS: 0.3

# Calculated
CASE_REYNOLDSNUMBER: None
CASE_REF_AREA: None
CASE_MOMENT_X: None
CASE_MOMENT_Y: None
CASE_MOMENT_Z: None