# Input
CASE_ROUGHNESS: 0.0004
CASE_CHARACTERISTIC_LENGTH: 0.431
CASE_VELOCITY: 20
CASE_ALTITUDE: 100
CASE_TEMPERATURE: 269.15
CASE_AOA: 0
CASE_MVD: 20
CASE_LWC: 0.000547
CASE_YPLUS: 0.3
PWS_REFINEMENT: 8 # mesh refinement level
# Icing time for each shot in a multishot run (seconds).
# The number of shots is determined by the length of the list below.
# CASE_MULTISHOT: [10, 20, 30]
